const PROJECT_INFO = {
    project_name: "SwordyType",
    project_description: "Typing speed test",
    project_version: "V1.14.0",
    development_start_date: "13 July, 2021",
    development_end_date: "7 August, 2021 (V1.0)",
    development_duration: "Total of 9 days (V1.0)",
    technologies_used: "HTML / CSS / JavaScript / FontAwesome / Google Fonts",
};

const DEVELOPER_INFO = {
    developer: "MoBakour",
    developer_github: "https://github.com/MoBakour",
    developer_discord: "swordax",
    developer_email: "mo.bakour@outlook.com",
    developer_linkedin: "https://www.linkedin.com/in/mobakour/",
};

const UPDATES = {
    "13 July, 2021": [
        "Started the project",
        "Designed the basic initial main interface",
        "Worked on the menu toggle",
        "Worked on the menu's appeariance and background",
        "Worked on the application's mechanism",
    ],
    "14 July, 2021": [
        "Finished the random word selection and injection into the interface",
        "Created the correct/wrong letter coloring system",
        "Created a button for reloading new words and redoing the test",
        "Fixed a bug where two letters were being taken together by changing the font family",
        "Created a basic auto scrolling system with issues",
        "Quited for a while for some reasons and for issues faced while developing",
    ],
    "1 August, 2021 [AM]": [
        "Back to working on the project",
        "Added a background for the current letter",
        "Made it that the test will start with 20 words, and an extra word will be selected and added everytime tester types a word",
        "Increased words displaying section width",
        "Made it that everyline will have 5 words and then break into the next line",
        "Developed the scrolling system so that every time you finish a line it will auto scroll to the next one (made it better than before)",
        "Made the auto scrolling behavior smooth",
        "Fixed a bug that used to happen when refreshing the test inside the app",
        "Designed a timer in the interface and developed the timing system",
        "Developed the processing mechanism to get the number of correct/incorrect words",
        "Added a title showing when hovering on the redo button",
    ],
    "1 August, 2021 [PM]": [
        "Worked on hiding and showing the results box and the test box",
        "Replaced an untypeable word from the words list with a new word",
        "Worked on developing the application mechanism",
    ],
    "2 August, 2021 [AM]": [
        "Fixed the bug where the last space in the line does not display",
        "Fixed all bugs in the auto scrolling system (hopefully)",
        "Made the autoscrolling system go up and down depending on the user's input, and made it in a profissional way",
        "Replaced the word 'church' with 'mosque' in the words list",
        "Highlighted the mistaken words alongside with the orangered text color given to them",
        "Fixed the interaction between the test starting / test ending / timer ... and all these stuff",
        "Designed the results box UI and finished it",
        "Made the results (WPM / Test Duration / Total, correct, and wrong characters count) all dynamic, still not the test type or the accuracy",
        "Added more transitions when jumping through sections and replaced the transitionend with a setTimeout",
        "Decreased all the transition durations in CSS and JS (intervals) to 3 milliseconds instead of 5",
        "Found some bugs to be fixed tomorrow inshallah",
    ],
    "2 August, 2021 [PM]": [
        "Fixed a bug occuring when refreshing the test during testing",
        "Developed the accuracy calculation algorithm and made the accuracy displayer dynamic",
        "Added titles for the results interface",
        "Modified the code a bit",
        "Created a flashing animation toggled when the time left is less than 5 seconds",
        "Created an enter refresh function (refresh on enter click)",
        "Fixed a bug that occurs on fast continuous refreshing by locking the refresh button for 1 second everytime its clicked",
        "Added sound effects whenever a key is pressed, one for correct input or backspace, another for mistakes",
    ],
    "3 August, 2021 [AM]": [
        "Designed the settings user interface in the menu and made the (theme, font size, timer, font family) controls designs",
        "Added new fonts that can be choosen form the settings",
        "Developed the mechanism of the font size / family / timer settings and made them dynamic",
        "Increased the test container width",
        "Made it that if you open the menu and the test is on-going the test will be stopped and refreshed",
        "Made some changes in the layout of the main interface",
        "Made it that when the test is refreshed the scrollTop will go to 0, which wasn't because of a bug caused by the changes in the layout",
        "Solved many encountered bugs",
    ],
    "4 August, 2021 [AM]": [
        "Made some changed to the settings layout",
        "Converted the website logo from PNG to SVG so that the color can be easily changed and customized",
        "Replaced the thin version of Roboto Mono font family with a thicker version",
        "Developed the theme changing system and added a number of themes",
        "Did some changes to the theme colors layout and converted some static colors to vars that can be controlled from the theme roots",
        "Got better versions of the key pressing sounds that work in a better way and made sure the performance is good with sounds on",
        "Made it that when the menu is opened, the menu content scrolltop becomes 0 incase it was left scrolled down in previous opens",
        "Added background transition effects in different elements in the website",
        "Made the footer credits a link to my (Swordax Sy) facebook account",
        "Edited the website title and made it SwordyType",
    ],
    "4 August, 2021 [PM]": [
        "Created a localStorage and set the current theme in it",
        "Changed the way of class setting for the theme buttons",
        "Added the test mode control in the settings and developed the test mode system",
        "Updated the algorithm responsible of knowing if the word was correct or wrong",
        "Added the test duration control in the settings and developed the test duration control system",
        "Changed the accuracy calculating algorithm from rounding to the the closest to rounding the the least",
        "Added a floor rounding (rounding to least) for the 2 minutes test WPM result to prevent decimal results",
        "Replaced the Candy World theme with the Lead theme",
        "Made the words stored in objects with extra information such as test name and text language direction",
        "Reorganized the words and renamed them with proper naming and got the arabic words",
    ],
    "5 August, 2021 [AM]": [
        "Created a random theme selecting system",
        "Created a user interface for the custom theme selector",
        "Created a custom theme selecting system",
        "Updated the theme saving to localStorage code and fixed some bugs related to it",
        "Disabled fire mode for development",
        "Modified the behavior of the hot mode so that backspace is always disabled",
        "Developed error system in case user tried to input an unvalid color number in custom theme control",
        "Simplified the algorithm used to calculate WPM and made a new one which solved the fire mode bug",
        "Enabled the fire mode",
        "Added mode notes in the settings",
        "Added test mode displayer in the results page",
        "Fixed a bug in fire mode by changing the timer interval to 100ms and decrementing the timer by 0.1 and ceiling the time to display",
    ],
    "6 August, 2021 [AM]": [
        "Fixed a bug in the WPM result caused by flooring the result by rounding the WPM instead of flooring it",
        "Worked on the letters layout",
    ],
    "6 August, 2021 [PM]": [
        "Worked on the letters layout and fixed all bugs related to it and fixed the font size/family changing problems",
        "Letters layout was made to not affect the arabic test so now arabic letters are fully supported",
        "Created the language selecting dropdown selector in the settings",
        "Developed the language selecting and switching system",
    ],
    "7 August, 2021 [AM]": [
        "Worked on the behaviors settings user interface and designed the switches format",
        "Developed customizable behaviors that cna be controled from the settings behavior system",
        "Behaviors developed : smooth auto-scrolling / show mistakes / enable sound / backspace to previous word",
        "Worked on the page main body layout to make it responsive to height resizing",
        "Made the website responsive enough (not targeting mobile users tho)",
        "Added a RegEx to detect mobile devices, in case the user was on mobile and the words were clicked, a keyboard from a fake input will appear",
        "Added one new theme into the pre-defined themes",
        "Organized the code and got it ready for production and deployment",
        "Created console credits function",
        "Added a browser tab icon (favicon) to the website",
        "Made leftToRight test words direction ltr and rightToLeft direction rtl",
        "Fixed some bugs caused by the edit of the layout previously",
        "Made the timer displaying and hiding fade in and out",
        "Developed local storing system for all the settings",
        /* V1.0 */ "SwordyType V1.0 successfully deployed on netlify",
    ],
    "8 August, 2021 [AM]": [
        "Removed the static 1100px width of the test words div",
        /* V1.01 */ "SwordyType V1.01 successfully deployed on netlify",
        "Fixed a bug that causes the WPM to be 0 in the first test",
        "Created enable_developer function for development and testing purposes",
        /* V1.02 */ "SwordyType V1.02 successfully deployed on netlify",
        "Added the website's version number to the developer_info() and made it dynamic",
        "Added error consoling in case a console function password was incorrect",
        /* V1.03 */ "SwordyType V1.03 successfully deployed on netlify",
    ],
    "10 August, 2021 [AM]": [
        "Added the russian language and tested it out",
        "Edited the user select property in the menu and made it that the texts are now selectable",
        "Fixed some issues in the page layout",
        "Fixed an issue in the responsive break-downs where one of them was coming too late",
        "Designed the discord-div and developed the discord id copy mechanism",
        "Changed all my contacts in the project's UI and code from my facebook account to my discord account",
        /* V1.1 */ "SwordyType V1.1 successfully deployed on netlify",
    ],
    "10 August, 2021 [PM]": [
        "Solved the bug of the self-opening behavior of the language dropdown selector",
        "Solved the bug of the timer showing after test refreshing even if its set to be hidden in the settings",
    ],
    "11 August, 2021 [AM]": [
        "Fixed some typos in the INFORMATION object in info.js",
        "Changed the developer_info() function to project_info() function and made it console.table the INFORMATION object instead of logging some text",
        "Added the project_updates() function and made it console.table the UPDATES object in info.js",
        "Re-ordered the dates of the updates in the UPDATES object in info.js and changed it from dd/mm/yy to mm/dd/yy so it appears more organized when logging in the console",
        /* V1.11 */ "SwordyType V1.11 successfully deployed on netlify",
        "Fixed a bug in the color customization system where the green and blue were switched in the wrong_clr selector",
        /* V1.12 */ "SwordyType V1.12 successfully deployed on netlify",
    ],
    "18 April, 2022": [
        "Fixed a bug in the index.html file",
        "Separated the DOM elements selectors constants into a different file [selectors.js]",
        "Moved the style sheets style.css and responsive.css into a new directory named styles",
        "Moved script.js, words.js, and selectors.js into a new directory named scripts",
        "Moved the website-logo image into a new directory named assets/images",
        "Moved the sounds directory into the assets directory",
        "Changed the format of the info.js updates constants days keys",
        "Modified the info.js file",
        "Created a README.md file",
        /* V1.13.0 */ "SwordyType V1.13.0 successfully deployed on netlify",
    ],
    "19 April, 2024": [
        "Extracted inline svg to separate svg image file and fetched it into the HTML file",
        "Updated credits to new socials",
        "Refactored a small bit of the code",
        /* V1.14.0 */ "Deployed SwordyType V1.14.0",
    ],
};
